/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmitCard {
  'id' : bigint,
  'downloadLink' : string,
  'instructions' : string,
  'organization' : string,
  'examDate' : Time,
  'examName' : string,
  'admitCardReleaseDate' : Time,
}
export interface ExamResult {
  'id' : bigint,
  'resultDeclarationDate' : Time,
  'categoryInfo' : string,
  'rollNumberRange' : string,
  'resultLink' : string,
  'organization' : string,
  'examName' : string,
}
export interface GovernmentScheme {
  'id' : bigint,
  'applicationProcess' : string,
  'ministryDepartment' : string,
  'description' : string,
  'schemeName' : string,
  'launchDate' : Time,
  'benefits' : string,
  'eligibilityCriteria' : string,
  'officialWebsite' : string,
}
export interface JobListing {
  'id' : bigint,
  'postName' : string,
  'organizationName' : string,
  'applicationStartDate' : Time,
  'applicationEndDate' : Time,
  'vacancyCount' : bigint,
  'qualificationRequirements' : string,
  'jobTitle' : string,
  'examDate' : Time,
  'location' : string,
  'officialWebsite' : string,
}
export interface NewsUpdate {
  'id' : bigint,
  'source' : string,
  'externalLink' : string,
  'headline' : string,
  'summary' : string,
  'publicationDate' : Time,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdmitCard' : ActorMethod<
    [string, string, Time, Time, string, string],
    bigint
  >,
  'addExamResult' : ActorMethod<
    [string, string, Time, string, string, string],
    bigint
  >,
  'addGovernmentScheme' : ActorMethod<
    [string, string, string, string, string, string, string, Time],
    bigint
  >,
  'addJobListing' : ActorMethod<
    [string, string, string, bigint, string, Time, Time, Time, string, string],
    bigint
  >,
  'addNewsUpdate' : ActorMethod<
    [string, string, Time, string, string, string],
    bigint
  >,
  'getLatestAdmitCards' : ActorMethod<[bigint], Array<AdmitCard>>,
  'getLatestExamResults' : ActorMethod<[bigint], Array<ExamResult>>,
  'getLatestGovernmentSchemes' : ActorMethod<[bigint], Array<GovernmentScheme>>,
  'getLatestJobListings' : ActorMethod<[bigint], Array<JobListing>>,
  'getLatestNewsUpdates' : ActorMethod<[bigint], Array<NewsUpdate>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];