/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AdmitCard = IDL.Record({
  'id' : IDL.Nat,
  'downloadLink' : IDL.Text,
  'instructions' : IDL.Text,
  'organization' : IDL.Text,
  'examDate' : Time,
  'examName' : IDL.Text,
  'admitCardReleaseDate' : Time,
});
export const ExamResult = IDL.Record({
  'id' : IDL.Nat,
  'resultDeclarationDate' : Time,
  'categoryInfo' : IDL.Text,
  'rollNumberRange' : IDL.Text,
  'resultLink' : IDL.Text,
  'organization' : IDL.Text,
  'examName' : IDL.Text,
});
export const GovernmentScheme = IDL.Record({
  'id' : IDL.Nat,
  'applicationProcess' : IDL.Text,
  'ministryDepartment' : IDL.Text,
  'description' : IDL.Text,
  'schemeName' : IDL.Text,
  'launchDate' : Time,
  'benefits' : IDL.Text,
  'eligibilityCriteria' : IDL.Text,
  'officialWebsite' : IDL.Text,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'postName' : IDL.Text,
  'organizationName' : IDL.Text,
  'applicationStartDate' : Time,
  'applicationEndDate' : Time,
  'vacancyCount' : IDL.Nat,
  'qualificationRequirements' : IDL.Text,
  'jobTitle' : IDL.Text,
  'examDate' : Time,
  'location' : IDL.Text,
  'officialWebsite' : IDL.Text,
});
export const NewsUpdate = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'externalLink' : IDL.Text,
  'headline' : IDL.Text,
  'summary' : IDL.Text,
  'publicationDate' : Time,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmitCard' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addExamResult' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addGovernmentScheme' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
      ],
      [IDL.Nat],
      [],
    ),
  'addJobListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        Time,
        Time,
        Time,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addNewsUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getLatestAdmitCards' : IDL.Func([IDL.Nat], [IDL.Vec(AdmitCard)], ['query']),
  'getLatestExamResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getLatestGovernmentSchemes' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GovernmentScheme)],
      ['query'],
    ),
  'getLatestJobListings' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getLatestNewsUpdates' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(NewsUpdate)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AdmitCard = IDL.Record({
    'id' : IDL.Nat,
    'downloadLink' : IDL.Text,
    'instructions' : IDL.Text,
    'organization' : IDL.Text,
    'examDate' : Time,
    'examName' : IDL.Text,
    'admitCardReleaseDate' : Time,
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Nat,
    'resultDeclarationDate' : Time,
    'categoryInfo' : IDL.Text,
    'rollNumberRange' : IDL.Text,
    'resultLink' : IDL.Text,
    'organization' : IDL.Text,
    'examName' : IDL.Text,
  });
  const GovernmentScheme = IDL.Record({
    'id' : IDL.Nat,
    'applicationProcess' : IDL.Text,
    'ministryDepartment' : IDL.Text,
    'description' : IDL.Text,
    'schemeName' : IDL.Text,
    'launchDate' : Time,
    'benefits' : IDL.Text,
    'eligibilityCriteria' : IDL.Text,
    'officialWebsite' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'postName' : IDL.Text,
    'organizationName' : IDL.Text,
    'applicationStartDate' : Time,
    'applicationEndDate' : Time,
    'vacancyCount' : IDL.Nat,
    'qualificationRequirements' : IDL.Text,
    'jobTitle' : IDL.Text,
    'examDate' : Time,
    'location' : IDL.Text,
    'officialWebsite' : IDL.Text,
  });
  const NewsUpdate = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'externalLink' : IDL.Text,
    'headline' : IDL.Text,
    'summary' : IDL.Text,
    'publicationDate' : Time,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmitCard' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addExamResult' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addGovernmentScheme' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
        ],
        [IDL.Nat],
        [],
      ),
    'addJobListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          Time,
          Time,
          Time,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addNewsUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getLatestAdmitCards' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AdmitCard)],
        ['query'],
      ),
    'getLatestExamResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getLatestGovernmentSchemes' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GovernmentScheme)],
        ['query'],
      ),
    'getLatestJobListings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getLatestNewsUpdates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NewsUpdate)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };