/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GovernmentScheme {
    id: bigint;
    applicationProcess: string;
    ministryDepartment: string;
    description: string;
    schemeName: string;
    launchDate: Time;
    benefits: string;
    eligibilityCriteria: string;
    officialWebsite: string;
}
export interface JobListing {
    id: bigint;
    postName: string;
    organizationName: string;
    applicationStartDate: Time;
    applicationEndDate: Time;
    vacancyCount: bigint;
    qualificationRequirements: string;
    jobTitle: string;
    examDate: Time;
    location: string;
    officialWebsite: string;
}
export interface NewsUpdate {
    id: bigint;
    source: string;
    externalLink: string;
    headline: string;
    summary: string;
    publicationDate: Time;
    category: string;
}
export type Time = bigint;
export interface ExamResult {
    id: bigint;
    resultDeclarationDate: Time;
    categoryInfo: string;
    rollNumberRange: string;
    resultLink: string;
    organization: string;
    examName: string;
}
export interface AdmitCard {
    id: bigint;
    downloadLink: string;
    instructions: string;
    organization: string;
    examDate: Time;
    examName: string;
    admitCardReleaseDate: Time;
}
export interface backendInterface {
    addAdmitCard(examName: string, organization: string, admitCardReleaseDate: Time, examDate: Time, downloadLink: string, instructions: string): Promise<bigint>;
    addExamResult(examName: string, organization: string, resultDeclarationDate: Time, resultLink: string, rollNumberRange: string, categoryInfo: string): Promise<bigint>;
    addGovernmentScheme(schemeName: string, ministryDepartment: string, description: string, eligibilityCriteria: string, benefits: string, applicationProcess: string, officialWebsite: string, launchDate: Time): Promise<bigint>;
    addJobListing(jobTitle: string, organizationName: string, postName: string, vacancyCount: bigint, qualificationRequirements: string, applicationStartDate: Time, applicationEndDate: Time, examDate: Time, officialWebsite: string, location: string): Promise<bigint>;
    addNewsUpdate(headline: string, summary: string, publicationDate: Time, source: string, category: string, externalLink: string): Promise<bigint>;
    getLatestAdmitCards(count: bigint): Promise<Array<AdmitCard>>;
    getLatestExamResults(count: bigint): Promise<Array<ExamResult>>;
    getLatestGovernmentSchemes(count: bigint): Promise<Array<GovernmentScheme>>;
    getLatestJobListings(count: bigint): Promise<Array<JobListing>>;
    getLatestNewsUpdates(count: bigint): Promise<Array<NewsUpdate>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmitCard(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmitCard(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmitCard(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addExamResult(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExamResult(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExamResult(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addGovernmentScheme(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addJobListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: Time, arg6: Time, arg7: Time, arg8: string, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJobListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJobListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addNewsUpdate(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsUpdate(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsUpdate(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getLatestAdmitCards(arg0: bigint): Promise<Array<AdmitCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestAdmitCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestAdmitCards(arg0);
            return result;
        }
    }
    async getLatestExamResults(arg0: bigint): Promise<Array<ExamResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestExamResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestExamResults(arg0);
            return result;
        }
    }
    async getLatestGovernmentSchemes(arg0: bigint): Promise<Array<GovernmentScheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestGovernmentSchemes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestGovernmentSchemes(arg0);
            return result;
        }
    }
    async getLatestJobListings(arg0: bigint): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestJobListings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestJobListings(arg0);
            return result;
        }
    }
    async getLatestNewsUpdates(arg0: bigint): Promise<Array<NewsUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNewsUpdates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNewsUpdates(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
